### ISSUE TITLE
New website format breaks categories 

### ISSUE THREAD

**Issue by Skelmis** [vcokltfre/tutorial#10]
Given the site appears to now have changed format the sidebar appears to be quite broken/out of order. See attached

https://gyazo.com/4a0d467dd84ec7f858666852b030ef2e
https://gyazo.com/939c50ab65b207679f79cd8d675bf2cd

**Comment by vcokltfre** [comment]
This is now fixed, it was an issue with the Compose theme, which I fixed in https://github.com/vcokltfre/compose
