### ISSUE TITLE
spelling fix: Yback

### ISSUE THREAD

**Issue by Skelmis** [vcokltfre/tutorial#4]
I was hoping to resolve this in #3 since I already have it open, however I could not find the source for the 404 page. 

Anyway, this page has a nice ole spelling error on it in the form of `Yback`
https://gyazo.com/45f07040828d826ffb91e8ce71d94cee

**Comment by Skelmis** [comment]
Edit: 
Found the source for it, although I'm not sure how *you* can fix it.

You can find the source for the spelling mistake [here](https://github.com/onweru/compose/blob/ba7520dfcd8bd5a2aeb2012739428ecdd74018ec/layouts/404.html#L4)

**Comment by vcokltfre** [comment]
This spelling works fine for me as discussed in Discord, and even so it's a thing with the compose theme so I'm closing this
