### ISSUE TITLE
Tutorial Request: `wait_for`

### ISSUE THREAD

**Issue by Skelmis** [vcokltfre/tutorial#5]
It would nice to feature a tutorial page for inline events, more commonly known as `wait_for`/getting responses within commands. This tutorial could be extremely simple, although I will include a checklist of things I think it should feature

- [ ] Waiting for a response from the user
- [ ] Waiting for the user to react to the command message or something similar with `on_reaction_...`
- [ ] A section on `check=func()` and how to use it
- [ ] A note on timeouts | what they mean | how to deal with them | `timeout=...`
- [ ] A note about how the events to wait for *aren't* prefixed with `on_` since that's just what dpy adds into them

**Comment by vcokltfre** [comment]
Done at last!
