### ISSUE TITLE
Tutorial Request: `convertors` & custom implementations

### ISSUE THREAD

**Issue by Skelmis** [vcokltfre/tutorial#7]
The usage of type hinting with discord.py is quite a nice topic to cover, and I feel it deserves a tutorial.
The page could cover the usage of built in type hinting & convertors before converging on some form of custom convertor.

- [ ] Type hinting to convertors
- [ ] Using convertors within a command

**Comment by vcokltfre** [comment]
Done! https://vcokltfre.dev/tutorial/14-converters
