### ISSUE TITLE
Tip Request: "Blocking calls"

### ISSUE THREAD

**Issue by pedro-anthony** [vcokltfre/tutorial#8]
There's lots of beginners using blocking libraries/functions in discord-py, Like the `requests` module, `time.sleep()`, instead of using their asynchronous counterparts.
There should be a page explaining the problem with blocking calls, and giving examples to the above, as they're quite commonly used.
This could also be integrated in the future as a general page about Async I/O.

**Comment by vcokltfre** [comment]
Done! this is live at https://vcokltfre.dev/tips/blocking
